---
version: '3.7'
services:

  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/opt/laffka

  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    volumes:
    - db-data:/data

volumes:
    db-data: